### ISSUE TITLE
Repair Python service tests after Wave 1 #93 service-layer extraction

### ISSUE THREAD

**Issue by briandenicola** [briandenicola/online-banking-demo#115]
## Problem

Wave 1 #93 extracted the Python service layers (routes/services/models/config) for `ai-service`, `budget-service`, `chatbot-service`, and `account-opening-service`, but the existing test files still import from `app.main` and rely on module-level singletons that no longer exist there. As a result, all four services have failing tests on `main` (verified 2026-05-13 against commit 39dfdbe).

These were pre-existing before Wave 2 — Wave 2 (#94 FastAPI Depends refactor) did not introduce regressions, but it also didn't repair them.

## Failures (baseline on main)

| Service | Failure | Root cause |
|---|---|---|
| **ai-service** | `tests/conftest.py` collection error | `ImportError: cannot import name 'RiskAssessment' from 'app.main'` — moved to `app.services.anomaly_service` |
| **budget-service** | 7 tests fail (3 in `TestCategorizeEndpoint`, 4 in `TestInsightsEndpoint`) | All `401 Unauthorized` — test client not sending JWT after route extraction |
| **chatbot-service** | `tests/test_llm_security.py` collection error | `ImportError: cannot import name 'get_user_transactions' from 'app.main'` — moved into `app.services.*` |
| **account-opening-service** | 8 tests fail in `tests/test_api.py` | `repository None` and admin-role assertions — DI changed during route extraction; tests still poke globals |

## Remediation

1. Update each `conftest.py` and test module to import from the new module locations (`app.services.*`, `app.routes.*`).
2. Wire test fixtures to use the FastAPI `Depends()` overrides introduced in #94 (use `app.dependency_overrides` for repositories/clients) instead of module-level globals.
3. For budget-service auth failures: provide a JWT fixture or override the auth dependency so `/categorize` and `/insights` return 200 in test mode.
4. Re-run `pytest` for each service and confirm green.

## Acceptance criteria

- `cd src/ai-service && pytest` — green (no collection errors, all tests pass)
- `cd src/budget-service && pytest` — 21/21 pass
- `cd src/chatbot-service && pytest` — green (no collection errors)
- `cd src/account-opening-service && pytest` — 136/136 pass

## Source
Discovered while validating Wave 2 #94. See session log 2026-05-13.

**Comment by briandenicola** [comment]
## Resolution Complete ✅

All 4 Python services have been repaired. Test results:

### ✅ ai-service
- **Commit:** 002e24b
- **Fix:** Updated test imports to use new module structure (app.services.anomaly_service, app.models.*)
- **Result:** All tests passing

### ✅ budget-service  
- **Commit:** 3481962
- **Fix:** Added JWT auth fixtures and updated imports to match extracted routes
- **Result:** 21/21 tests passing

### ✅ chatbot-service
- **Commit:** c7435e8
- **Fix:** Updated test imports to pull from app.services.* instead of app.main
- **Result:** All tests passing

### ✅ account-opening-service
- **Commit:** e4fc3b4
- **Fix:** 
  - Restored missing audit trail endpoint (accidentally dropped during Wave 1 extraction)
  - Added FastAPI dependency overrides using async functions for proper DI pattern
  - Overrode get_repository, get_redis_client, get_blob_service_client, get_state_machine
- **Result:** 136/136 tests passing

## Pattern Identified

The core issue across all services was the FastAPI Depends() pattern introduced in Wave 1. Tests need to use app.dependency_overrides with async override functions (not lambda returns) to match the async dependency signatures.

Example:
```python
async def override_repository():
    return mock_repo

app.dependency_overrides[get_repository] = override_repository
```

All acceptance criteria met. Ready to close.

**Comment by briandenicola** [comment]
All acceptance criteria met. Closing issue.
